name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycalphad matplotlib numpy

    - name: Run CALPHAD simulation
      run: |
        mkdir -p results
        python calphad/run_dp_ods.py || echo "CALPHAD run failed"

    - name: Upload CALPHAD results
      uses: actions/upload-artifact@v3
      with:
        name: calphad-results
        path: results/calphad_phase_fractions.png

    - name: Test FISPACT parser (with dummy data)
      run: |
        echo "CONTACT DOSE RATE 1.2E+01 µSv/h" > fispact/test_output.txt
        python scripts/parse_fispact.py fispact/test_output.txt
